### ISSUE TITLE
fake-useragent is broken

### ISSUE THREAD

**Issue by frankmedia** [areed1192/finance-news-aggregator#2]
[fake-useragent](https://fake-useragent.herokuapp.com/browsers/0.1.11) --> is a 404

Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11
Traceback (most recent call last):
  File "/Users/frank/opt/anaconda3/lib/python3.9/site-packages/fake_useragent/utils.py", line 154, in load
    for item in get_browsers(verify_ssl=verify_ssl):
  File "/Users/frank/opt/anaconda3/lib/python3.9/site-packages/fake_useragent/utils.py", line 99, in get_browsers
    html = html.split('<table class="w3-table-all notranslate">')[1]
IndexError: list index out of range

**Comment by cdromain** [comment]
The solution is to update the `fake-useragent` package, i.e. replace the old version (0.1.11) with the [latest working version](https://pypi.org/project/fake-useragent/) (2.0+).
